### ISSUE TITLE
Make eventyay-video autodeployment work

### ISSUE THREAD

**Issue by marcoag** [fossasia/eventyay-video#135]
There are currently 3 issues we should fix to make auto-deployment work:

1. Current deployment doesnt work when using the image `eventyay/eventyay-video:development`, we should fix this to make sure these images work.
2. Watchtower redeployments seem to fail with "npm not found" we need to investigate how watchtower does this redeployment and see how to fix this.
3. We changed ports in https://github.com/fossasia/eventyay-video/commit/8ca1a66009a7e788dad6ecd4198d3f0087b129b3, we should revert this change as it breaks the `Dockerfile-dev.yaml` builds and current `docker-compose.yaml` in root that are useful for local development. Then we should update the server nginx so the port matches in the reverted config: `8375`.

**Comment by odkhang** [comment]
Hi @marcoag, 
on the third point, about the port.

In local, webapp will open a socket connection with backend and we do not use SSL for websocket connection.

But in dev and prod environment, SSL is required, and we setup SSL at nginx, so if we open web socket on port 8375, it will directly to backend, not through nginx and we got an issue here. the reason why we change the port connection that make webapp connect with backend via nginx to enable SSL.
For easy to understand:
webapp - open websocket to port 8375 -> backend (no SSL and will cause an error because webapp is running on SSL config)

webapp - open websocket to port 8443 on nginx -> nginx reverse proxy to 8375 to the backend, it working fine as currently.

So I suggest we should note somewhere in the document tell developer to change the port connection same with port opened by backend

cc @mariobehling

**Comment by odkhang** [comment]
Hi @marcoag,
https://github.com/fossasia/eventyay-video/pull/136 to fix point 2 error when watchtower redeploy webapp.
for the first issue, could you please give me more detail how to preproduce or what is the log error of it.

cc @mariobehling

**Comment by mariobehling** [comment]
> 1. Current deployment doesnt work when using the image `eventyay/eventyay-video:development`, we should fix this to make sure these images work.

In the standard config when we merge a pull request into the development branch a new docker image gets built and deployed to https://video-dev.eventyay.com. So, instead of triggering the build yourself it gets triggered automatically. It can be tested by merging a PR into development.
